name: second_github_action
on: [push]
jobs:
  aws_cp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA3BGDAV5JJQDYSE7S
          aws-secret-access-key: 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
          aws-region: us-east-1
      - name: Upload to s3
        run: aws s3 cp ./Capture2.PNG s3://ff4-bucket/ff4-demo-folder/
